/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PasswordEntry {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'username' : string,
  'password' : string,
  'createdAt' : Time,
  'notes' : string,
}
export interface PremiumCode {
  'code' : string,
  'createdAt' : Time,
  'isUsed' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'contact' : [] | [string],
  'premiumUntil' : [] | [Time],
  'lastLoginAt' : Time,
  'isPremium' : boolean,
  'email' : [] | [string],
  'loginCount' : bigint,
  'bonusBalance' : bigint,
  'pendingPremium' : boolean,
  'registeredAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activatePremium' : ActorMethod<[Principal, string], undefined>,
  'addDefaultProfile' : ActorMethod<[], undefined>,
  'addEntry' : ActorMethod<[string, string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPremiumCode' : ActorMethod<[string, string], undefined>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<[string], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmailByPrincipal' : ActorMethod<[Principal, string], [] | [string]>,
  'getEntries' : ActorMethod<[], Array<PasswordEntry>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPendingPremiumRequests' : ActorMethod<
    [string],
    Array<[Principal, UserProfile]>
  >,
  'getPremiumCodes' : ActorMethod<[string], Array<PremiumCode>>,
  'getPremiumDaysRemaining' : ActorMethod<[], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginEmailUser' : ActorMethod<[string, string], boolean>,
  'redeemPremiumCode' : ActorMethod<[string], undefined>,
  'registerEmailUser' : ActorMethod<[string, string, string], boolean>,
  'requestPremium' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'spendBonus' : ActorMethod<[], undefined>,
  'updateEntry' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'validateCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];