/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'premiumUntil' : IDL.Opt(Time),
  'isPremium' : IDL.Bool,
  'pendingPremium' : IDL.Bool,
});
export const PasswordEntry = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
});
export const PremiumCode = IDL.Record({
  'code' : IDL.Text,
  'createdAt' : Time,
  'isUsed' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activatePremium' : IDL.Func([IDL.Principal], [], []),
  'addDefaultProfile' : IDL.Func([], [], []),
  'addEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPremiumCode' : IDL.Func([IDL.Text], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(PasswordEntry)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPendingPremiumRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getPremiumCodes' : IDL.Func([], [IDL.Vec(PremiumCode)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemPremiumCode' : IDL.Func([IDL.Text], [], []),
  'requestPremium' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'validateCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'premiumUntil' : IDL.Opt(Time),
    'isPremium' : IDL.Bool,
    'pendingPremium' : IDL.Bool,
  });
  const PasswordEntry = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
  });
  const PremiumCode = IDL.Record({
    'code' : IDL.Text,
    'createdAt' : Time,
    'isUsed' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activatePremium' : IDL.Func([IDL.Principal], [], []),
    'addDefaultProfile' : IDL.Func([], [], []),
    'addEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPremiumCode' : IDL.Func([IDL.Text], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(PasswordEntry)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPendingPremiumRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getPremiumCodes' : IDL.Func([], [IDL.Vec(PremiumCode)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemPremiumCode' : IDL.Func([IDL.Text], [], []),
    'requestPremium' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'validateCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };